package nl.hu.bdsd.consumerCreator.constants;

public interface IStopWords {

	public static String[] STOPWORDS = ("eens gewoonweg hebben al jouwe voorheen sindsdien verscheidene om nu echter etc"
			+ " eerdat gemoeten tegen zijzelf maakten namelijk zelfs gewoon ik zodat enkel iemand derde lijkt hem word"
			+ " eerste overige honderd weldra zes voor gedurende wegens ergens kunt geleden ander duizend mw had genoeg"
			+ " omtrent ons alhoewel vooral zowat aldaar mochten zullen thans in omstreeks er hunne redelijk bepaald"
			+ " tussen vooralsnog de altoos eerder nee meer derhalve gehad van ook niemand per dikwijls maakt rond toch"
			+ " volgend wier hierom vrij onszelf na haar binnenin deze aangaande tweede andere mits inmiddels te boven"
			+ " dhr vol maken die hierin sedert mag beide opnieuw hierna tegenover nog hoewel zelf aldus elk vooruit"
			+ " veeleer vijftig neem bv omhoog gekund mezelf hun moeten overeind weg klaar op iedereen ondertussen"
			+ " nemen paar behoudens voordien hij zeven wederom zal u even kun missen dan vandaan misschien recent vanaf"
			+ " miss als zijn nadat hadden liever mijn vanuit behalve hetzelfde geen zodra geweest mocht toenmalig nv"
			+ " hedden allebei terwijl anderszins ooit buiten blijken ondanks hierbeneden eer bovendien ikzelf vijfde zei"
			+ " twee hoe je me konden betreffende daarvanlangs weinig alle bijv of erdoor over doen ze daaruit welk niet"
			+ " werder was hier toe willen nochtans veertig welke beiden zult alles voorop maar vroeg bent lijken uw"
			+ " maakte ieder bovengenoemd etcetera zo voorts eigenlijk wie dat binnen jezelf rondom daarin af gelijk"
			+ " overal meest deed daarop worden whatever anders beetje een hen wilden want naar onzeker volgens tijdens"
			+ " kunnen krachtens zulke enigszins aangezien wordt tiende vanwege dus hierboven mijnent alleen afgelopen"
			+ " eerlang aan zulk nooit sommige we elke voorbij wanneer jijzelf doorgaand is noch samen bij en minder"
			+ " enig totdat daarna wijzelf pas werden haarzelf drie laatst maak overigens via door wat voordat jouw"
			+ " juist precies achterna bijna zich hijzelf vijf hebt omver tenzij tot vier mijner alsnog zou hare"
			+ " gemogen erg heb mij uitgezonderd alias zoals steeds blijkbaar vierde waar inzake achter heeft meestal"
			+ " altijd verschillende deden inderdaad tamelijk heel jullie wezen kon hemzelf achte enige daardoor onder"
			+ " ofschoon wel daarnet bovenvermeld iedere ge reeds dit slechts men tien niets waren net nam daarheen"
			+ " later jij jou bovenal zij spoedig iets mr bovenstaand werd daarom verder omlaag voordezen evenwel onze"
			+ " nergens moest waarom daar ja wij nogal opzij vooraf moet weer veel toenmaals zichzelf vaak gauw mijzelf"
			+ " beneden niks wiens der uit ongeveer ben wil kan met eerst toen mrs vaakwat doch intussen mogen negen"
			+ " zijne eigen mevr doe moesten eveneens doet vervolgens omdat dertig zonder sinds zouden zelfde tja"
			+ " waarschijnlijk zeker het few these ours y don you'd d been his i why's with could not couldn't didn't"
			+ " shan't into should've if have doing during he'll shouldn yourself there's am hers who's such isn't other"
			+ " out aren he'd our mustn't more i've them the yours ought when's once having will nor just himself at"
			+ " you'll only down ain didn that'll they're below yourselves no then my we're all you're t mustn i'll how"
			+ " we'd so haven mightn same needn't can re were do wouldn each own we ll shan its it this through very"
			+ " myself had under what's after m her where those as their is your hasn for from herself you doesn't"
			+ " mightn't haven't let's him in be they'd isn they should are because being here wasn before did here's"
			+ " weren both about which ourselves there theirs he's it's me aren't when shouldn't above by and that than"
			+ " some i'd don't against they'll on hadn't that's doesn won themselves but where's up or itself of wasn't"
			+ " has wouldn't needn whom now over she we'll off she's o they've we've who again to a any couldn weren't"
			+ " between s while was ve would you've how's he she'd what an until won't hadn most she'll ma i'm too hasn't"
			+ " further does why").split(" ");
	
}
